charkour/zundo

README.md
src/factory.ts
src/index.ts
src/middleware.ts
src/utils.ts
stories/bears.stories.tsx

Pass a second argument to undoMiddleware that is an array of keys that are on your undo store state interface that will not be tracked in history.
there are some todo's there because I couldn't get the types to work perfectly. 
usage:
```tsx
const useStore = create<StoreState>(
undoMiddleware(
set => ({ ... }),
{ omit: ['field1', 'field2'] }
)
);
```
Closes #8

allow ability to omit fields from being tracked in history

---

README.md
package-lock.json
src/factory.ts
src/middleware.ts
src/utils.ts
stories/cool-off.stories.tsx
stories/debounce.stories.tsx

- Adds`coolOffDurationMs` to options to allow debouncing of actions
- Using the term "cool-off" instead of "debounce" because I think it's more descriptive. You are setting for how many milliseconds history will be disabled after each change in state
**Important:** Even with this setting disabled, this PR still changes the behaviour of Zundo. Any changes that happen instantly together will only be recorded as a single item in history.
To explain what I mean, take this piece of code:
```javascript
increasePopulation()
increasePopulation()
increasePopulation()
```
Before this PR, 3 items would be added to history and you have to undo 3 times to get back to 0
After this PR (even with `coolOffDurationMs` as `undefined`), only one new item is added to history and one undo is required to get …

Cool-off period

---

README.md
package.json
src/factory.ts
src/middleware.ts
src/types.ts
src/utils.ts
stories/allow-unchanged.stories.tsx
stories/bears.stories.tsx
stories/bees.stories.tsx

Replaces omit (still functional) with exclude and adds the option to include keys.
This was a [requested feature](https://github.com/charkour/zundo/issues/26) and makes a lot of sense for complex stores. I opted for the names exclude/include as over whitelist/blacklist because I feel they are clearer.
None! 🎉
Omit is still a usable options but the documentation has been updated warning developers not to use it anymore.
There were no existing tests for omit and I haven't added any new ones here. I did however update the storybook to use include for the bees example.
@charkour Not sure if there are issues with this but I noticed that the filtered state contains (and with the new includes option now sometimes doesn't contain) the actions `redo`, `undo`, etc. I'm not sure if this is …

Replaced omit with exclude and include

---

apps/web/pages/separate.tsx
packages/zundo/__tests__/options.test.ts
packages/zundo/__tests__/zundo.test.ts
packages/zundo/src/temporal.ts
pnpm-lock.yaml

This fixes one of the issues described in #15 reported by @skrat where the temporal store would not re-render.

create new arrays

---

packages/zundo/__tests__/zundo.test.ts
packages/zundo/package.json
packages/zundo/src/temporal.ts

- Adds tests to make sure state are applied in the correct order when using `undo(step)` and `redo(step)`
fixes #59

fix step bug not reversing order

---

packages/zundo/__tests__/options.test.ts
packages/zundo/src/index.ts
packages/zundo/src/temporal.ts
packages/zundo/src/types.ts

more efficiencies 
868 B --> 862 B (save 4 bytes) Inline setters in index.ts
862 B --> 859 B (save 3 bytes) return a configWithTemporal object to remove `_store`
859 --> 855 B (save 4 bytes) assign to property rather than create variable in index.ts
855 --> 854 B (save 1 byte) remove curried zustand create in zundo.ts
853 --> 847 B (save 6 bytes) rename __handleUserSet to __handleSet

switch config for better types and save bytes

---

.github/workflows/build.yml
apps/docs/package.json
apps/web/package.json
package.json
packages/eslint-config-custom/package.json
packages/ui/package.json
packages/zundo/README.md
packages/zundo/package.json
packages/zundo/tsconfig.json
pnpm-lock.yaml

and bump deps.
888 B --> 887 B

drop node 14 support

---

apps/web/package.json
apps/web/pages/persist.tsx
apps/web/pages/reactive.tsx
apps/web/pages/separate.tsx
apps/web/pages/setstate.tsx
packages/zundo/__tests__/createVanillaTemporal.test.ts
packages/zundo/src/index.ts
packages/zundo/src/temporal.ts
packages/zundo/src/types.ts
pnpm-lock.yaml

remove objects. save 19 bytes

---

apps/web/package.json
package.json
pnpm-lock.yaml

Related to #96. Caused an issue with running examples

move immer to root to fix broken examples from 8608dd94c5597588e38950

---

README.md
__tests__/options.test.ts
examples/web/package.json
examples/web/pages/throttle.tsx
examples/web/pages/wrapped.tsx
pnpm-lock.yaml

fix async test

---

pnpm-lock.yaml
src/index.ts

use ...args

---

__tests__/react.test.tsx
src/temporal.ts

The past and future states are now copied only if undoing or redoing is actually possible. This should slightly improve performance.
Relevant issue: https://github.com/charkour/zundo/issues/111

Copy past and future states only if necessary

---

README.md
__tests__/options.test.ts
examples/web/package.json
examples/web/pages/diff.tsx
examples/web/tsconfig.json
package.json
pnpm-lock.yaml
src/temporal.ts
src/types.ts

addresses #113
819 B --> 837 B (2.20% increase)
Add `diff` option to track state deltas

feat: add `diff` option to track state deltas

---

package.json

#143
In v2.0.1, I tried to make a change to support ESM and CJS, but misconfigured the package.json so only ESM was supported.

add support for both esm and cjs

---

README.md

This updates the docs to have consistent formatting per lines and use proper [TS usage with zustand](https://github.com/pmndrs/zustand#typescript-usage).

fix TS usage on docs, small formatting

---

src/index.ts
src/temporal.ts
src/types.ts
tests/__tests__/options.test.ts

This PR removes the `_handleSet` internal property of `_TemporalState` in favor of defining `handleSet` within `temporal` (index.ts). 
This is beneficial from a complexity-reducing standpoint: `_handleSet` no longer needs to be a member of the temporal state, and its functionality is easily discoverable and readable within `temporal`.
This change also allows us to remove the type assertion required for accessing private internal properties of `_TemporalState` when using `getState()`, which returns type `TemporalState`.

[v3] remove _handleSet from _TemporalState

---

tests/__tests__/options.test.ts

In the scope of this test, only `console.error` is defined. 
Any time the `temporal` store's setter is called, `console.error` should be called.

fix spying on wrong function

---

.github/workflows/build.yml
README.md

#166 
_Does the `sed` command change the file for the other runs in the matrix?_ Nope! Looking at the Action runs, the `Build` step correctly includes DTS for zustand v4.2.0 and latest.

Add Test Matrix

---

.github/workflows/build.yml

- Remove middle Node version; assumes that if v16 works and v20 works, any intermediate versions will also work. 
- Use latest zustand v5

update matrix and version

---

.github/workflows/build.yml
.vscode/settings.json
README.md
examples/web/package.json
examples/web/pages/options.tsx
package.json
pnpm-lock.yaml
size/package.json
tests/__tests__/options.test.ts
tests/package.json
tests/vitest.config.ts

local ts version and run prettier

bump deps and remove v5 support

---

tests/__mocks__/zustand/index.ts
tests/__tests__/createVanillaTemporal.test.ts
tests/__tests__/options.test.ts
tests/__tests__/react.test.tsx
tests/__tests__/zundo.test.ts
tests/tsconfig.json
tests/vitest.config.ts
tests/vitest.setup.ts

- Use latest zustand testing docs: https://github.com/pmndrs/zustand/blob/main/docs/guides/testing.md
- Use vitest globals
- Migrate from deprecated `act` to new import
- Tweak some tests in React to improve how we are accessing values in zustand stores (this breaks in zustand v5)

use latest zustand testing docs
