- README.md
- package-lock.json
- package.json
- src/factory.ts
- src/index.ts
- src/middleware.ts
- stories/bears.stories.tsx
- stories/bees.stories.tsx
- stories/multiple-undo.stories.tsx
- stories/no-zustand-import.stories.tsx
update documentation and add the ability to use multiple undoable stores in the same app.
closes #1
> Multiple undo stores

- package.json
this prevent's errors when installing zundo
> remove force pnpm

- package.json
- pnpm-lock.yaml
- src/index.ts
- src/middleware.ts
- stories/multiple-undo.stories.tsx
> support zustand v4

- packages/zundo/README.md
- packages/zundo/__tests__/createVanillaTemporal.test.ts
- packages/zundo/__tests__/options.test.ts
- packages/zundo/__tests__/zundo.test.ts
- packages/zundo/src/index.ts
- packages/zundo/src/temporal.ts
- packages/zundo/src/types.ts
- updates docs
- test more edge cases
temporalState --> temporalStatus
> small tweaks to types and docs

- apps/web/package.json
- apps/web/pages/chained.tsx
- apps/web/pages/index.tsx
- packages/zundo/README.md
- packages/zundo/__mocks__/zustand/vanilla.js
- packages/zundo/__tests__/createVanillaTemporal.test.ts
- packages/zundo/__tests__/options.test.ts
- packages/zundo/__tests__/zundo.test.ts
- packages/zundo/package.json
- packages/zundo/src/index.ts
- packages/zundo/src/temporal.ts
- pnpm-lock.yaml
fixes #62
I am honestly new to Zundo (I just downloaded it 1 hour ago) and also not really an expert when it comes to Zustand as well 😅 
The [changelogs](https://github.com/pmndrs/zustand/compare/v4.2.0...v4.3.0) are quite insightful if you wanna double check things. Though really unexpected changes for a supposedly "minor" release...
I was able to make the tests all green without major modifications and I quickly double checked whether it works in my application via `npm link` and it works all fine. Though I use Zundo in its most basic form so maybe you need to double check the more advanced usecase of this lib
> fix: support zustand@4.3.x

- apps/web/pages/setstate.tsx
- packages/zundo/package.json
- packages/zundo/src/index.ts
- packages/zundo/src/temporal.ts
- pnpm-lock.yaml
fixes #67 
Add the modified setState to the user's store.
> add modified setState

- packages/zundo/__tests__/options.test.ts
- packages/zundo/src/index.ts
- packages/zundo/src/temporal.ts
- packages/zundo/src/types.ts
962 B --> 945 B (difference of 17 Bytes)
> shave some bytes

- apps/web/pages/separate.tsx
- packages/zundo/README.md
- packages/zundo/__tests__/options.test.ts
- packages/zundo/src/temporal.ts
- packages/zundo/src/types.ts
> init states

- apps/web/package.json
- apps/web/pages/persist.tsx
- apps/web/pages/subscribeWithSelector.tsx
- packages/zundo/README.md
- packages/zundo/__tests__/createVanillaTemporal.test.ts
- packages/zundo/package.json
- packages/zundo/src/index.ts
- packages/zundo/src/temporal.ts
- packages/zundo/src/types.ts
- packages/zundo/vitest.config.ts
- pnpm-lock.yaml
865 B --> 888 B (increase 23 B)
> Add middleware to temporal store

- packages/zundo/src/index.ts
- packages/zundo/src/temporal.ts
- packages/zundo/src/types.ts
> shave 9 bytes

- packages/zundo/README.md
- packages/zundo/__tests__/options.test.ts
- packages/zundo/src/index.ts
- packages/zundo/src/temporal.ts
- packages/zundo/src/types.ts
878 B --> 877 B
Not sure why it reduces the bundle
> rename internal types

- packages/zundo/src/index.ts
- packages/zundo/src/temporal.ts
- packages/zundo/src/types.ts
> simplify types, refactor _handleSet heuristics

- src/temporal.ts
> shave 2 bytes

- __tests__/createVanillaTemporal.test.ts
- src/index.ts
- src/temporal.ts
- src/types.ts
> switch to temporal state creator

- examples/web/package.json
- package.json
- pnpm-lock.yaml
821 B --> 819 B
Verify it works with latest zustand version
> shave 2 bytes by updating deps

- README.md
- __tests__/options.test.ts
- examples/web/pages/diff.tsx
- src/temporal.ts
- src/types.ts
> add diffing during undo and redo

- README.md
- src/types.ts
This PR updates the types as mentioned [here](https://github.com/charkour/zundo/issues/140). 
I also included some updates to the docs. If you'd prefer I separate these docs updates into a separate PR, I'm happy to do so!
When I was first reading the docs for `zundo` there were some points of initial confusion for me, so some of my suggested updates are to clarify those things.
Thank you!
> fix equality fn type and update docs

- examples/web/package.json
- package.json
- pnpm-lock.yaml
- tests/package.json
- tests/vitest.config.ts
- tests/vitest.setup.ts
> switch to happy-dom and bump deps

- README.md
> make update about reactive data

- .gitignore
- package.json
- tests/__tests__/react.test.tsx
- tests/package.json
- tests/vitest.config.ts
- tsconfig.json
- simplify gitignore
- tweak tsconfig
- remove unused deps
- support zustand v5
> some updates

- .github/workflows/build.yml
- README.md
- examples/web/package.json
- examples/web/pages/chained.tsx
- examples/web/pages/diff.tsx
- examples/web/pages/index.tsx
- examples/web/pages/input.tsx
- examples/web/pages/nested.tsx
- examples/web/pages/persist.tsx
- examples/web/pages/reactive.tsx
- examples/web/pages/separate.tsx
- examples/web/pages/setstate.tsx
- examples/web/pages/throttle.tsx
- examples/web/pages/wrapped.tsx
- package.json
- pnpm-lock.yaml
- src/index.ts
- tests/__mocks__/zustand/index.ts
- tests/__tests__/options.test.ts
- tests/package.json
- tests/tsconfig.json
- tests/vitest.setup.ts
> initially support v5
